project:
  title: "report"
  output-dir: "_output"

standalone: true
self-contained: true

## Generic options
lang: ru-RU
number-sections: true
toc: true
toc-title: "Содержание"
toc-depth: 2

## Crossref customization
crossref:
  lof-title: "Список иллюстраций"
  lot-title: "Список таблиц"
  lol-title: "Листинги"

## Bibliography
bibliography:
  - bib/cite.bib

csl: _resources/csl/gost-r-7-0-5-2008-numeric.csl

## Formats
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: false
    toc-depth: 2
    lof: true  # Список иллюстраций
    lot: true  # Список таблиц
    documentclass: scrreprt
    papersize: a4
    fontsize: 12pt
    linestretch: 1.5
    babel-lang: russian
    babel-otherlangs: english
    cite-method: biblatex
    biblatexoptions:
      - backend=biber
      - langhook=extras
      - autolang=other*
    csquotes: true
    indent: true
    header-includes: |
      \usepackage{indentfirst}
      \usepackage{float}
      \floatplacement{figure}{H}
      \usepackage{libertine}
    auto-install: false

  docx:
    toc: true
    number-sections: true
    toc-depth: 2


    


